name: Run Python Script

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Use the version of Python required

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw gspread oauth2client  # List all your dependencies

      - name: Run script
        run: python your_script.py  # Replace 'your_script.py' with your script filename
